In [ ]:
###Lab12 26Mar25

In [27]:
#Write a NumPy program to create a structured array from given student name,height,class and their data types with some 
#missing values and show the data.Fill out the missing values and output the data.
import numpy as np

# Define the data type with a float for height and float for class
data_type = [('name', 'S15'), ('class', float), ('height', float)]

# Create a structured numpy array with 4 students, with some missing values
students = np.zeros(4, dtype=data_type)

# Assign data with missing values (represented by np.nan for height and class)
students['name'] = ['amiths', 'dhanush', 'hemanth', 'hit']
students['class'] = [5, np.nan, 5, 5]  # Using np.nan for missing class for 'dhanush'
students['height'] = [48.5, 53, np.nan, 40]  # Missing height for 'hemanth'

# Output the original data with missing values
print("Original Data (with missing values):")
print(students)

# Fill missing values:
# - For 'class', replace missing values (NaN) with the most common class (5).
# - For 'height', replace missing values with the mean height.

# Fill missing 'class' with 5 (most common class) where class is NaN
students['class'] = np.where(np.isnan(students['class']), 5, students['class'])

# Fill missing 'height' with the mean of the existing height values
mean_height = np.nanmean(students['height'])
students['height'] = np.where(np.isnan(students['height']), mean_height, students['height'])

# Output the data after filling missing values
print("\nData after filling missing values:")
print(students)

Original Data (with missing values):
[(b'amiths',  5., 48.5) (b'dhanush', nan, 53. ) (b'hemanth',  5.,  nan)
 (b'hit',  5., 40. )]

Data after filling missing values:
[(b'amiths',  5., 48.5       ) (b'dhanush', nan, 53.        )
 (b'hemanth',  5., 47.16666667) (b'hit',  5., 40.        )]

In [31]:
import numpy as np
import pandas as pd
churn_data=pd.read_csv('churn.csv',index_col=0)
print(churn_data.head())

   customerID tenure        Contract PaperlessBilling  \
1  8260-NGFNY    One  Month-to-month               No
2  2359-QWQUL     39        One year              Yes
3  6598/RFFVI      2        One year               No
4  IXSTS-8780      6  Month-to-month              Yes
5  2674/MIAHT   Four  Month-to-month              Yes

             PaymentMethod  MonthlyCharges  TotalCharges  gender  \
1             Mailed check            25.2         25.20  Female
2  Credit card (automatic)           104.7       4134.85  Female
3  Credit card (automatic)            19.3         28.30    Male
4         Electronic check            90.1        521.30  Female
5             Mailed check            80.3        324.20  Female

   SeniorCitizen Partner  ... PhoneService     MultipleLines InternetService  \
1            0.0      No  ...           No  No phone service             DSL
2            0.0     Yes  ...          Yes                No     Fiber optic
3            0.0      No  ...          Yes                No              No
4            0.0      No  ...          Yes               Yes     Fiber optic
5            0.0      No  ...          Yes               Yes     Fiber optic

        OnlineSecurity         OnlineBackup     DeviceProtection  \
1                   No                   No                   No
2                  Yes                   No                  Yes
3  No internet service  No internet service  No internet service
4                   No                  Yes                   No
5                   No                  Yes                   No

           TechSupport          StreamingTV      StreamingMovies Churn
1                   No                   No                   No   Yes
2                  Yes                  Yes                  Yes   Yes
3  No internet service  No internet service  No internet service   Yes
4                   No                  Yes                   No   Yes
5                   No                   No                   No    No

[5 rows x 21 columns]

In [49]:
import numpy as np
import pandas as pd
churn_data=pd.read_csv('churn.csv',index_col=0)
print(churn_data.tail())

     customerID tenure        Contract PaperlessBilling  \
253  9318-NKNFC    One  Month-to-month              Yes
254  9067-SQTNS     44        One year               No
255  9067-SQTNS     44        One year               No
256  9067-SQTNS     44        One year               No
257  9067-SQTNS     44        One year               No

                 PaymentMethod  MonthlyCharges  TotalCharges gender  \
253               Mailed check           18.85         18.85   Male
254  Bank transfer (automatic)           20.60        926.00   Male
255  Bank transfer (automatic)           20.60        926.00   Male
256  Bank transfer (automatic)           20.60        926.00   Male
257  Bank transfer (automatic)           20.60        926.00   Male

     SeniorCitizen Partner  ... PhoneService MultipleLines InternetService  \
253            0.0      No  ...          Yes            No              No
254            0.0     Yes  ...          Yes            No              No
255            0.0     Yes  ...          Yes            No              No
256            0.0     Yes  ...          Yes            No              No
257            0.0     Yes  ...          Yes            No              No

          OnlineSecurity         OnlineBackup     DeviceProtection  \
253  No internet service  No internet service  No internet service
254                  Yes                  Yes  No internet service
255                  Yes                  Yes  No internet service
256                  Yes                  Yes  No internet service
257                  Yes                  Yes  No internet service

             TechSupport          StreamingTV      StreamingMovies Churn
253  No internet service  No internet service  No internet service   Yes
254  No internet service                  Yes  No internet service    No
255  No internet service                  Yes  No internet service    No
256  No internet service                  Yes  No internet service    No
257  No internet service                  Yes  No internet service    No

[5 rows x 21 columns]
Index(['customerID', 'tenure', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'gender', 'SeniorCitizen', 'Partner',
       'Dependents', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Churn'],
      dtype='object')

In [53]:
print(churn_data.columns)

Index(['customerID', 'tenure', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'gender', 'SeniorCitizen', 'Partner',
       'Dependents', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Churn'],
      dtype='object')

In [51]:
print(churn_data.tenure)

1       One
2        39
3         2
4         6
5      Four
       ...
253     One
254      44
255      44
256      44
257      44
Name: tenure, Length: 257, dtype: object

In [69]:
#Count total number of dupliate records in th  e dataframe
print(len(churn_data) - len(churn_data.drop_duplicates()))

7

In [85]:
#Count duplicate records based on attribute (customerID)
import pandas as pd
df = churn_data['customerID'].duplicated()
print(df)
print(sum(df))
print(churn_data[df])

1      False
2      False
3      False
4      False
5      False
       ...
253    False
254     True
255     True
256     True
257     True
Name: customerID, Length: 257, dtype: bool
7
     customerID tenure  Contract PaperlessBilling              PaymentMethod  \
47   9067-SQTNS     44  One year               No  Bank transfer (automatic)
48   9067-SQTNS     44  One year               No  Bank transfer (automatic)
49   9067-SQTNS     44  One year               No  Bank transfer (automatic)
254  9067-SQTNS     44  One year               No  Bank transfer (automatic)
255  9067-SQTNS     44  One year               No  Bank transfer (automatic)
256  9067-SQTNS     44  One year               No  Bank transfer (automatic)
257  9067-SQTNS     44  One year               No  Bank transfer (automatic)

     MonthlyCharges  TotalCharges gender  SeniorCitizen Partner  ...  \
47             20.6         926.0   Male            0.0     Yes  ...
48             20.6         926.0   Male            0.0     Yes  ...
49             20.6         926.0   Male            0.0     Yes  ...
254            20.6         926.0   Male            0.0     Yes  ...
255            20.6         926.0   Male            0.0     Yes  ...
256            20.6         926.0   Male            0.0     Yes  ...
257            20.6         926.0   Male            0.0     Yes  ...

    PhoneService MultipleLines InternetService OnlineSecurity OnlineBackup  \
47           Yes            No              No            Yes          Yes
48           Yes            No              No            Yes          Yes
49           Yes            No              No            Yes          Yes
254          Yes            No              No            Yes          Yes
255          Yes            No              No            Yes          Yes
256          Yes            No              No            Yes          Yes
257          Yes            No              No            Yes          Yes

        DeviceProtection          TechSupport StreamingTV  \
47   No internet service  No internet service         Yes
48   No internet service  No internet service         Yes
49   No internet service  No internet service         Yes
254  No internet service  No internet service         Yes
255  No internet service  No internet service         Yes
256  No internet service  No internet service         Yes
257  No internet service  No internet service         Yes

         StreamingMovies Churn
47   No internet service    No
48   No internet service    No
49   No internet service    No
254  No internet service    No
255  No internet service    No
256  No internet service    No
257  No internet service    No

[7 rows x 21 columns]

In [87]:
df = churn_data['tenure'].duplicated()
print(df)
print(sum(df))
print(churn_data[df])

1      False
2      False
3      False
4      False
5      False
       ...
253     True
254     True
255     True
256     True
257     True
Name: tenure, Length: 257, dtype: bool
186
     customerID tenure        Contract PaperlessBilling  \
9    5854-KSRBJ     70        Two year               No
10   5054-IEXZT    One  Month-to-month              Yes
12   7235-NXZCP      2  Month-to-month              Yes
16   9374-YOLBJ    One  Month-to-month               No
20   6513-EECDB    One  Month-to-month              Yes
..          ...    ...             ...              ...
253  9318-NKNFC    One  Month-to-month              Yes
254  9067-SQTNS     44        One year               No
255  9067-SQTNS     44        One year               No
256  9067-SQTNS     44        One year               No
257  9067-SQTNS     44        One year               No

                 PaymentMethod  MonthlyCharges  TotalCharges  gender  \
9                 Mailed check           25.40       1782.05    Male
10            Electronic check           75.35         75.35    Male
12                Mailed check           74.85        156.40    Male
16            Electronic check           19.25         19.25  Female
20            Electronic check           73.55         73.55    Male
..                         ...             ...           ...     ...
253               Mailed check           18.85         18.85    Male
254  Bank transfer (automatic)           20.60        926.00    Male
255  Bank transfer (automatic)           20.60        926.00    Male
256  Bank transfer (automatic)           20.60        926.00    Male
257  Bank transfer (automatic)           20.60        926.00    Male

     SeniorCitizen Partner  ... PhoneService MultipleLines InternetService  \
9              0.0     Yes  ...          Yes           Yes              No
10             0.0      No  ...          Yes            No     Fiber optic
12             1.0      No  ...          Yes           Yes     Fiber optic
16             0.0     Yes  ...          Yes            No              No
20             1.0     Yes  ...          Yes           Yes     Fiber optic
..             ...     ...  ...          ...           ...             ...
253            0.0      No  ...          Yes            No              No
254            0.0     Yes  ...          Yes            No              No
255            0.0     Yes  ...          Yes            No              No
256            0.0     Yes  ...          Yes            No              No
257            0.0     Yes  ...          Yes            No              No

          OnlineSecurity         OnlineBackup     DeviceProtection  \
9    No internet service  No internet service  No internet service
10                    No                  Yes                   No
12                    No                   No                   No
16                   Yes                  Yes  No internet service
20                    No                   No                   No
..                   ...                  ...                  ...
253  No internet service  No internet service  No internet service
254                  Yes                  Yes  No internet service
255                  Yes                  Yes  No internet service
256                  Yes                  Yes  No internet service
257                  Yes                  Yes  No internet service

             TechSupport          StreamingTV      StreamingMovies Churn
9    No internet service  No internet service  No internet service    No
10                    No                   No                   No   Yes
12                    No                   No                   No   Yes
16   No internet service                  Yes  No internet service    No
20                    No                   No                   No   Yes
..                   ...                  ...                  ...   ...
253  No internet service  No internet service  No internet service   Yes
254  No internet service                  Yes  No internet service    No
255  No internet service                  Yes  No internet service    No
256  No internet service                  Yes  No internet service    No
257  No internet service                  Yes  No internet service    No

[186 rows x 21 columns]

In [89]:
df = churn_data['Contract'].duplicated()
print(df)
print(sum(df))
print(churn_data[df])

1      False
2      False
3       True
4       True
5       True
       ...
253     True
254     True
255     True
256     True
257     True
Name: Contract, Length: 257, dtype: bool
254
     customerID tenure        Contract PaperlessBilling  \
3    6598/RFFVI      2        One year               No
4    IXSTS-8780      6  Month-to-month              Yes
5    2674/MIAHT   Four  Month-to-month              Yes
6    6077-BDPXA      3  Month-to-month              Yes
8    7547-EKNFS     42  Month-to-month              Yes
..          ...    ...             ...              ...
253  9318-NKNFC    One  Month-to-month              Yes
254  9067-SQTNS     44        One year               No
255  9067-SQTNS     44        One year               No
256  9067-SQTNS     44        One year               No
257  9067-SQTNS     44        One year               No

                 PaymentMethod  MonthlyCharges  TotalCharges  gender  \
3      Credit card (automatic)           19.30         28.30    Male
4             Electronic check           90.10        521.30  Female
5                 Mailed check           80.30        324.20  Female
6             Electronic check           70.15        194.20  Female
8    Bank transfer (automatic)           95.25       3959.35    Male
..                         ...             ...           ...     ...
253               Mailed check           18.85         18.85    Male
254  Bank transfer (automatic)           20.60        926.00    Male
255  Bank transfer (automatic)           20.60        926.00    Male
256  Bank transfer (automatic)           20.60        926.00    Male
257  Bank transfer (automatic)           20.60        926.00    Male

     SeniorCitizen Partner  ... PhoneService MultipleLines InternetService  \
3              0.0      No  ...          Yes            No              No
4              0.0      No  ...          Yes           Yes     Fiber optic
5              0.0      No  ...          Yes           Yes     Fiber optic
6              0.0      No  ...          Yes            No     Fiber optic
8              0.0     Yes  ...          Yes           Yes     Fiber optic
..             ...     ...  ...          ...           ...             ...
253            0.0      No  ...          Yes            No              No
254            0.0     Yes  ...          Yes            No              No
255            0.0     Yes  ...          Yes            No              No
256            0.0     Yes  ...          Yes            No              No
257            0.0     Yes  ...          Yes            No              No

          OnlineSecurity         OnlineBackup     DeviceProtection  \
3    No internet service  No internet service  No internet service
4                     No                  Yes                   No
5                     No                  Yes                   No
6                     No                   No                   No
8                     No                  Yes                  Yes
..                   ...                  ...                  ...
253  No internet service  No internet service  No internet service
254                  Yes                  Yes  No internet service
255                  Yes                  Yes  No internet service
256                  Yes                  Yes  No internet service
257                  Yes                  Yes  No internet service

             TechSupport          StreamingTV      StreamingMovies Churn
3    No internet service  No internet service  No internet service   Yes
4                     No                  Yes                   No   Yes
5                     No                   No                   No    No
6                     No                   No                   No    No
8                     No                  Yes                   No   Yes
..                   ...                  ...                  ...   ...
253  No internet service  No internet service  No internet service   Yes
254  No internet service                  Yes  No internet service    No
255  No internet service                  Yes  No internet service    No
256  No internet service                  Yes  No internet service    No
257  No internet service                  Yes  No internet service    No

[254 rows x 21 columns]

In [91]:
#missing values in each column
print(churn_data.isnull().sum())

customerID           0
tenure               0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges      10
TotalCharges        15
gender               0
SeniorCitizen        5
Partner              0
Dependents           0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Churn                0
dtype: int64

In [97]:
#
churn_data.isna()

,customerID,tenure,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,gender,SeniorCitizen,Partner,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Churn
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
254,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
255,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
256,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
257,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [117]:
help(pd.isna)

Help on function isna in module pandas.core.dtypes.missing:

isna(obj: 'object') -> 'bool | npt.NDArray[np.bool_] | NDFrame'
    Detect missing values for an array-like object.

    This function takes a scalar or array-like object and indicates
    whether values are missing (``NaN`` in numeric arrays, ``None`` or ``NaN``
    in object arrays, ``NaT`` in datetimelike).

    Parameters
    ----------
    obj : scalar or array-like
        Object to check for null or missing values.

    Returns
    -------
    bool or array-like of bool
        For scalar input, returns a scalar boolean.
        For array input, returns an array of boolean indicating whether each
        corresponding element is missing.

    See Also
    --------
    notna : Boolean inverse of pandas.isna.
    Series.isna : Detect missing values in a Series.
    DataFrame.isna : Detect missing values in a DataFrame.
    Index.isna : Detect missing values in an Index.

    Examples
    --------
    Scalar arguments (including strings) result in a scalar boolean.

    >>> pd.isna('dog')
    False

    >>> pd.isna(pd.NA)
    True

    >>> pd.isna(np.nan)
    True

    ndarrays result in an ndarray of booleans.

    >>> array = np.array([[1, np.nan, 3], [4, 5, np.nan]])
    >>> array
    array([[ 1., nan,  3.],
           [ 4.,  5., nan]])
    >>> pd.isna(array)
    array([[False,  True, False],
           [False, False,  True]])

    For indexes, an ndarray of booleans is returned.

    >>> index = pd.DatetimeIndex(["2017-07-05", "2017-07-06", None,
    ...                           "2017-07-08"])
    >>> index
    DatetimeIndex(['2017-07-05', '2017-07-06', 'NaT', '2017-07-08'],
                  dtype='datetime64[ns]', freq=None)
    >>> pd.isna(index)
    array([False, False,  True, False])

    For Series and DataFrame, the same type is returned, containing booleans.

    >>> df = pd.DataFrame([['ant', 'bee', 'cat'], ['dog', None, 'fly']])
    >>> df
         0     1    2
    0  ant   bee  cat
    1  dog  None  fly
    >>> pd.isna(df)
           0      1      2
    0  False  False  False
    1  False   True  False

    >>> pd.isna(df[1])
    0    False
    1     True
    Name: 1, dtype: bool